spring.application.name=demo-phongkham-nhakhoa
# Cấu hình H2 Database
spring.datasource.url=jdbc:h2:mem:nhakhoa_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate tự động tạo bảng dựa trên các lớp @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Bật giao diện web của H2 tại đường dẫn /h2-console
spring.h2.console.enabled=true