spring.application.name=demo-phongkham-nhakhoa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:h2:mem:phongkham
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=phong
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update